### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'jload'

### ISSUE THREAD

**Issue by Anya-RB-Chen** [XZhang97666/AlpaCare#5]
I'm training the model from scratch using the scripts under `training/training_alpaca.py`, and there is actually no `jload` function in the `utils.py`. May I please know how to solve this issue?

```
Traceback (most recent call last):
  File "/lustre07/scratch/myname/AlpaCare/train_alpaca.py", line 223, in <module>
    train()
  File "/lustre07/scratch/myname/AlpaCare/train_alpaca.py", line 215, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre07/scratch/myname/AlpaCare/train_alpaca.py", line 178, in make_supervised_data_module
    train_dataset = SupervisedDataset(tokenizer=tokenizer, data_path=data_args.data_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre07/scratch/rubing/AlpaCare/train_alpaca.py", line 134, in __init__
    list_data_dict = utils.jload(data_path)
                     ^^^^^^^^^^^
AttributeError: module 'utils' has no attribute 'jload'
```

**Comment by Bostoncake** [comment]
Seems like they didn't include this method into the published codebase. Simply add the following funtion to `utils.py` would work out:
```
def jload(filename):
    with open(filename, 'r') as file:
        data = json.load(file)
    return data
```
